# Generated by Django 4.2.7 on 2023-11-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='subject_assignment_marks',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject_exam_marks',
            field=models.CharField(max_length=1),
        ),
    ]
