# Generated by Django 4.2.7 on 2023-11-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_studentresult_subject_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='subject_assignment_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject_exam_marks',
            field=models.FloatField(default=0),
        ),
    ]
